[build]
  publish = "client/source"

[functions]
  directory = "server/endpoint"
  node_bundler = "esbuild"

[[redirects]]
  from = "/CDN/:splat"
  to = "/*"
  status = 200
  
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200