[build]
  publish = "client/source"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "server/endpoint"
  node_bundler = "esbuild"

[[redirects]]
  from = "/CDN/*"
  to = "/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200